---
- name: mariadb role
  tags:
    - mariadb
  block:

  # install
  - ansible.builtin.import_tasks: mariadb-install.yml

  # systemd
  - ansible.builtin.import_tasks: mariadb-systemd.yml

  # databases
  - ansible.builtin.import_tasks: mariadb-databases.yml

  # users
  - ansible.builtin.import_tasks: mariadb-users.yml