---
- tags: [role-mariadb-users-root]
  when: mariadb_root_pw != None
  block:

  # assert
  - name: Assertions for mariadb-users-root
    ansible.builtin.assert:
      that:
      - ansible_facts['hostname'] is defined
      quiet: true

  # remove anonymous
  - name: Remove anonymous database users
    when: mariadb_root_pw != None
    ansible.mysql.mysql_user:
      name: ""
      host_all: true
      login_user: root
      login_password: "{{ mariadb_root_pw }}"
      state: absent

  # root pw
  - name: Set MariaDB root password
    ansible.mysql.mysql_user:
      name: root
      login_password: "{{ mariadb_root_pw }}"
      login_user: root
      login_unix_socket: /var/run/mysqld/mysqld.sock
      check_implicit_admin: true
      state: present

  # disallow remote root login
  - name: Disallow root login remotely
    loop:
    - "{{ ansible_facts['hostname'] }}"
    - "127.0.0.1"
    - "::1"
    ansible.mysql.mysql_user:
      name: root
      host: "{{ item }}"
      login_user: root
      login_password: "{{ mariadb_root_pw }}"
      state: absent